#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
#namePrefix: edge-sandbox-

commonLabels:
  component: vcs-awskms
  group: core
  instance: local
  project: trustbloc

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- path: vcs/replacements.yml
  source: null
  targets: null
- source:
    kind: Secret
    name: vcs-wildcard-cert-awskms
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: vcs-awskms

replicas:
- count: 1
  name: vcs-awskms

configMapGenerator:
- behavior: merge
  envs:
  - vcs/config.env
  name: vcs-env-awskms
- files:
  - ../certs/ca.crt
  name: vcs-ca-cert-awskms

secretGenerator:
- files:
  - ../certs/tls.crt
  - ../certs/tls.key
  name: vcs-wildcard-cert-awskms
  type: kubernetes.io/tls
- files:
  - ../keys/vcs-kms-key.pem
  name: vcs-kms-key-awskms

transformers:
- sedtransform.yml
- sedb64transform.yml

resources:
- ../../common/vcs-awskms
- vcs/ingress.yml

patchesStrategicMerge:
- vcs/add-ca.yml
- vcs/add-key.yml
